// Centralized Design Tokens
// In a top-tier enterprise app, these might be generated by a tool like Style Dictionary 
// from Figma tokens, or fetched from a specific company @design-system package.

export const themeTokens = {
    light: {
        '--bg-primary': '#ffffff',   // Pure bright white background
        '--bg-surface': '#ffffff',   // Pure white for cards/surfaces
        '--text-primary': '#111827', // Very dark slate for high contrast readability
        '--text-secondary': '#6b7280',// Medium gray for secondary info
        '--accent-primary': '#0ea5e9',// Vibrant Sky Blue accent for a pop of color
        '--accent-hover': '#0284c7', // Deeper blue for hover states
        '--danger': '#ef4444',       
        '--border-light': '#e5e7eb', // Soft border color
        '--nav-bg': 'rgba(255, 255, 255, 0.90)', // Glassmorphism nav background
    },
    dark: {
        '--bg-primary': '#09090b',   // Premium ultra-dark (almost black) background
        '--bg-surface': '#18181b',   // Slightly lighter dark for cards (zinc-900)
        '--text-primary': '#f8fafc', // Crisp white text
        '--text-secondary': '#a1a1aa', // Soft gray text for secondary
        '--accent-primary': '#38bdf8', // Brighter Sky Blue accent for dark mode contrast
        '--accent-hover': '#7dd3fc', // Even lighter on hover
        '--danger': '#f87171',
        '--border-light': '#27272a', // Subtle dark border (zinc-800)
        '--nav-bg': 'rgba(24, 24, 27, 0.90)', // Glassmorphism dark nav
    }
};

/**
 * Utility function to apply a set of tokens to the DOM
 * Injects a dynamic <style> block into the head to ensure CSS variables
 * are correctly registered globally at the :root level for all modules.
 * @param {Object} tokens - An object of CSS variables and their values
 */
export const applyThemeTokens = (tokens) => {
    let styleEl = document.getElementById('dynamic-theme');
    if (!styleEl) {
        styleEl = document.createElement('style');
        styleEl.id = 'dynamic-theme';
        document.head.appendChild(styleEl);
    }

    const cssVariables = Object.entries(tokens)
        .map(([key, value]) => `${key}: ${value};`)
        .join('\n    ');

    styleEl.innerHTML = `
:root {
    ${cssVariables}
}
    `;
};
